MVCeTicaret/MVCeTicaret/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCeTicaret.Models
{
    public class Product
    {
        [Key]
        public int ProductID { get; set; }

        [Required,MaxLength(200)]
        public string Name { get; set; }

        [Required,ForeignKey("Supplier")]
        public int SupplierID { get; set; }

        [Required,ForeignKey("SubCategory")]
        public int SubCategoryID { get; set; }

        [Required,MaxLength(20)]
        public string QuantityPerUnit { get; set; }


        [Required,Column(TypeName = "money")]
        public decimal UnitPrice { get; set; }

        [Column(TypeName ="money")]
        public decimal? OldPrice { get; set; }

        [MaxLength(20)]
        public string UnitWeight { get; set; }

        [MaxLength(20)]
        public string Size { get; set; }


        public decimal Discount { get; set; }

        public int UnitInStock { get; set; }

        public int? UnitOnOrder { get; set; }

        public bool? ProductAvailable { get; set; }

        [Required,MaxLength(500)]
        public string ImageUrl { get; set; }

        [Required,MaxLength(200)]
        public string AltText { get; set; }

        [Required,MaxLength(300)]
        public string ShortDescription { get; set; }

        [Required,MaxLength(2000)]
        public string LongDescription { get; set; }

        [MaxLength(500)]
        public string Picture1 { get; set; }

        [MaxLength(500)]
        public string Picture2 { get; set; }

        [MaxLength(500)]
        public string Picture3 { get; set; }

        [MaxLength(500)]
        public string Picture4 { get; set; }

        [MaxLength(250)]
        public string Notes { get; set; }


        public virtual SubCategory SubCategory { get; set; }
        public virtual Supplier Supplier { get; set; }

        public virtual ICollection<OrderDetail> OrderDetails { get; set; }

        public virtual ICollection<RecentlyView> RecentlyViews { get; set; }

        public virtual ICollection<Review> Reviews { get; set; }

        public virtual ICollection<WishList> WishLists { get; set; }

    }
}

MVCeTicaret/MVCeTicaret/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCeTicaret.Models;

namespace MVCeTicaret.Controllers
{
    public class ProductController : Controller
    {
        Context db;
        public ProductController()
        {
            db = new Context();
        }
       
        public ActionResult Product(int id)
        {
            
            return View(db.Products.Where(x=>x.SubCategoryID==id).ToList());
        }

        public ActionResult ProductDetail(int id)
        {
            ViewData["Reviews"] = db.Reviews.Where(x => x.ProductID == id && x.IsDeleted==false).ToList();
            return View(db.Products.Find(id));
        }

        
    }
}

MVCeTicaret/MVCeTicaret/Controllers/ShoppingController.cs
using MVCeTicaret.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCeTicaret.Controllers
{
    public class ShoppingController : Controller
    {
        Context db;
        public ShoppingController()
        {
            db = new Context();
        }
        [HttpPost]
        public ActionResult AddToCart(int id, FormCollection frm)
        {
            if (Session["OnlineKullanici"] == null)
                return RedirectToAction("Login", "Login");

            int miktar = Convert.ToInt32(frm["quantity"]);

            //TODO:CustomerID dinamik hale getirilecek...
            OrderDetail od = db.OrderDetails.Where(x => x.ProductID == id && x.IsCompleted == false && x.CustomerID==3 ).FirstOrDefault();
            
            if (od==null)
            {
                od = new OrderDetail();
                od.CustomerID = 3;//TODO: Dinamik hale getirilecek....
                od.ProductID = id;
                od.OrderDate = DateTime.Now;
                od.IsCompleted = false;
                od.UnitPrice = db.Products.Find(id).UnitPrice;
                od.Discount = db.Products.Find(id).Discount;

                if (db.Products.Find(id).UnitInStock >= miktar)
                    od.Quantity = miktar;
                else
                    od.Quantity = db.Products.Find(id).UnitInStock;

                od.TotalAmount = od.Quantity * od.UnitPrice * (1 - od.Discount);
                db.OrderDetails.Add(od);
            }
            else
            {
               if(db.Products.Find(id).UnitInStock > od.Quantity + miktar)
                {
                    od.Quantity += miktar;
                    od.TotalAmount = od.Quantity * od.UnitPrice * (1 - od.Discount);
                }
            }
            db.SaveChanges();
            //TODO: CustomerID dinamik olarak çekilecek...
            return View(db.OrderDetails.Where(x=>x.CustomerID==3 && x.IsCompleted==false).ToList());
        }

        public ActionResult AddToWishList(int id)
        {
            WishList wl = db.WishLists.FirstOrDefault(x => x.ProductID == id && x.CustomerID == 3 && x.IsActive == true);
            if (wl == null)
            {
                wl = new WishList();
                wl.CustomerID = 3; //TODO: Dinamik hale getirilecek....
                wl.ProductID = id;
                wl.IsActive = true;

                db.WishLists.Add(wl);
                db.SaveChanges();
            }
           

            return View(db.WishLists.Where(x=>x.CustomerID==3 && x.IsActive==true).ToList());
        }
    }
}

MVCeTicaret/MVCeTicaret/Views/Product/Product.cshtml
@model IEnumerable<MVCeTicaret.Models.Product>

@{
    ViewBag.Title = "Product";
}

<div class="container">
    <div class="row" style="margin-top:50px">
        @{ 
            foreach (var item in Model)
            {
                <div class="col-md-3">
                    <div class="thumbnail">
                        <img src="@Url.Content(item.ImageUrl)" alt="@Url.Content(item.AltText)" />
                        <div class="caption">
                            <h4 style="height:50px">
                                @item.Name - @string.Format("{0:C2}", item.UnitPrice)
                            </h4>
                            <p style="height:60px;overflow:auto";>
                                @item.ShortDescription
                            </p>
                            <p>                               
                                @Html.ActionLink("Ürün Detayı","ProductDetail",new { id = item.ProductID},new { @class="btn btn-danger form-control"})
                            </p>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>

MVCeTicaret/MVCeTicaret/Views/Product/ProductDetail.cshtml
@model MVCeTicaret.Models.Product
@{
    ViewBag.Title = "ProductDetail";
}

<div class="container">
    <div class="row" style="margin-top:50px">
        <div class="col-md-4">
            <div class="thumbnail">
                <img style="border:outset" src="@Url.Content(Model.ImageUrl)" alt="@Url.Content(Model.AltText)" id="@Model.ProductID" />
            </div>
        </div>
        <div class="col-md-8">
            <h2>@Model.Name</h2>
            @{
                for (int i = 0; i < 5; i++)
                {
                    <span class="glyphicon glyphicon-star" style="font-size:17pt;"></span>
                }
            }

            <br /><br /><br />

            <p class="lead">
                <strong>Fiyatı: </strong> @string.Format("{0:C2}", Model.UnitPrice)
            </p>
            <p class="lead">
                <span style="background-color:lightgray;">
                    <strong>Stok Miktarı: </strong> @Model.UnitInStock @Model.QuantityPerUnit
                </span>
            </p>

            @using (Html.BeginForm("AddToCart", "Shopping", new { id = Model.ProductID }, FormMethod.Post))
            {
              <p class="lead">
                <strong>Miktar: </strong>
                @{
                    if (Model.UnitInStock == 0)
                    {
                        <input type="number" name="quantity" value="0" min="0" max="@Model.UnitInStock" onchange="denetle(this,@Model.UnitInStock)" />
                    }
                    else
                    {
                        <input type="number" name="quantity" value="1" min="1" max="@Model.UnitInStock" onchange="denetle(this,@Model.UnitInStock)" />
                    }
                }

                 </p>

                <br /><br />
                if (Model.UnitInStock == 0)
                {
                    <input type="submit" disabled value="Sepete Ekle" class="btn btn-lg btn-warning" />
                }
                else
                {
                    <input type="submit" value="Sepete Ekle" class="btn btn-lg btn-warning" />
                }

                <a href="@Url.Action("AddToWishList","Shopping",new { id=Model.ProductID })" class="btn btn-danger btn-lg">İstek listesine ekle</a>
            }
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <ul class="nav nav-tabs ">
                    <li class="active"><a data-toggle="tab" href="#description">Açıklama</a></li>
                    <li><a data-toggle="tab" href="#review">Yorumlar</a></li>
                </ul>
                <div class="tab-content">
                    <div id="description" class="tab-pane fade in active">
                        <p>@Html.Raw(Model.LongDescription)</p>
                    </div>
                    <div id="review" class="tab-pane fade ">
                        <p>
                            @{
                                foreach (var item in ViewData["Reviews"] as IEnumerable<MVCeTicaret.Models.Review>)
                                {
                                    <li>
                                        <p><strong>@item.Name</strong></p>
                                        <p>@item.Comment</p>
                                    </li>
                                }
                            }
                            </p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

@section scripts{
    <script>
        function denetle(inputElement, maxValue) {
            var value = $(inputElement).val();
            if (value > maxValue)
                $(inputElement).val(maxValue);

            if (value < 0)
                $(inputElement).val(0);
        }
    </script>        
}